server:
  port: 9000
spring:
  application:
    name: restaurant-discovery-service
  datasource:
    url: jdbc:mysql://localhost:3306/food_delivery_db
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true