server:
  port: 9002
spring:
  application:
    name: payment-service
  datasource:
    url: jdbc:mysql://localhost:3306/food_delivery_db
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update