server:
  port: 9001
spring:
  application:
    name: order-service
com:
  foodDelivery:
    running:
      payment:
        service: http://localhost:9002
      orderDelivery:
        service: http://localhost:9003