server:
  port: 9001
spring:
  application:
    name: order-service
  datasource:
    url: jdbc:mysql://localhost:3306/food_delivery_db
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
com:
  foodDelivery:
    running:
      payment:
        service: http://localhost:9002
      orderDelivery:
        service: http://localhost:9003